theme = "tokyonight_storm"

[editor]
bufferline = "multiple"
true-color = true
color-modes = true
cursorline = true
soft-wrap.enable = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true

[editor.lsp]
display-messages = true

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
"*" = ["move_prev_word_start", "move_next_word_end", "search_selection"]
"@" = [
  "move_prev_word_start",
  "move_next_word_end",
  "search_selection",
  "global_search",
]
tab = ":buffer-next"
S-tab = ":buffer-previous"
A-w = ":buffer-close"

[keys.normal.space]
w = ":write"
q = ":quit"
l = ":toggle lsp.display-inlay-hints"

[keys.normal.space.u]
n = ":toggle line-number relative absolute"
